package mail

import "fmt"

var (
	ToCreate = []string{
		"AuditEventOutcome",
		"AuditEventOutcomeDetail",
		"AuditEventSeverity",
		"AuditEventSubType",
		"AuditEventType",
		"BasicResourceType",
		"BenefitNetwork",
		"BenefitTerm",
		"BenefitType",
		"BenefitUnit",
		"BindingStrength N",
		"BiologicallyderivedProductPropertyTypeCodes",
		"BiologicallyderivedProductStatus",
		"BiologicallyderivedProductcodes",
		"BiologicallyderivedproductdispenseMatchStatus",
		"BiologicallyderivedproductdispenseOriginRelationship",
		"BiologicallyderivedproductdispensePerformerFunction",
		"BiologicallyderivedproductdispenseStatus",
		"BodySite",
		"BodystructureBodylandmarkorientationClockfacePosition",
		"BodystructureCode",
		"BodystructureRelativeLocation",
		"BundleType N",
		"C80Facilitycodes",
		"C80PracticeCodes",
		"CapabilityFormatType N",
		"CapabilityStatementKind N",
		"CarePlanActivityPerformed",
		"CarePlanCategory",
		"CarePlanIntent",
		"CareTeamCategory",
		"CareTeamStatus",
		"Catalogtype",
		"CdshooksIndicator",
		"CertaintyRating",
		"CertaintyType",
		"CharacteristicCombination",
		"CharacteristicOffset",
		"ChargeitemBillingcodes",
		"ChargeitemStatus",
		"CitationArtifactClassifier",
		"CitationClassificationType",
		"CitationStatusType",
		"CitationSummaryStyle",
		"CitedArtifactAbstractType",
		"CitedArtifactClassificationType",
		"CitedArtifactPartType",
		"CitedArtifactStatusType",
		"CitedMedium",
		"ClaimCareteamrole",
		"ClaimDecision",
		"ClaimDecisionReason",
		"ClaimException",
		"ClaimInformationcategory",
		"ClaimModifiers",
		"ClaimOutcome",
		"ClaimSubtype",
		"ClaimType",
		"ClaimUse",
		"ClinicalFindings",
		"ClinicalUseDefinitionCategory",
		"ClinicalUseDefinitionType",
		"ClinicalimpressionChangePattern",
		"ClinicalimpressionPrognosis",
		"ClinicalimpressionStatusReason",
		"CodeSearchSupport",
		"CodesystemContentMode N",
		"CodesystemHierarchyMeaning N",
		"ColorCodes",
		"CombinedDoseForm",
		"CommonTags",
		"CommunicationCategory",
		"CommunicationNotDoneReason",
		"CommunicationRequestStatusReason",
		"CommunicationTopic",
		"CompartmentType",
		"CompositeMeasureScoring",
		"CompositionAttestationMode",
		"CompositionStatus",
		"ConceptMapRelationship",
		"ConceptPropertyType N",
		"ConceptSubsumptionOutcome",
		"ConceptmapAttributeType N",
		"ConceptmapPropertyType N",
		"ConceptmapUnmappedMode",
		"ConcreteFhirTypes",
		"ConditionCategory",
		"ConditionClinical",
		"ConditionCode",
		"ConditionOutcome",
		"ConditionPreconditionType",
		"ConditionQuestionnairePurpose",
		"ConditionSeverity",
		"ConditionStage",
		"ConditionStageType",
		"ConditionVerStatus",
		"ConditionalDeleteStatus N",
		"ConditionalReadStatus N",
		"ConformanceExpectation",
		"ConsentAction",
		"ConsentCategory",
		"ConsentContentClass",
		"ConsentContentCode",
		"ConsentDataMeaning",
		"ConsentPolicy",
		"ConsentProvisionType",
		"ConsentStateCodes",
		"ConsentVerification",
		"ConsistencyType",
		"ConstraintSeverity N",
		"ContactPointSystem N",
		"ContactPointUse N",
		"ContainerCap",
		"ContainerMaterial",
		"ContractAction",
		"ContractActionstatus",
		"ContractActorrole",
		"ContractAssetcontext",
		"ContractAssetscope",
		"ContractAssetsubtype",
		"ContractAssettype",
		"ContractContentDerivative",
		"ContractDecisionMode",
		"ContractDefinitionSubtype",
		"ContractDefinitionType",
		"ContractExpirationType",
		"ContractLegalstate",
		"ContractPartyRole",
		"ContractPublicationstatus",
		"ContractScope",
		"ContractSecurityCategory",
		"ContractSecurityClassification",
		"ContractSecurityControl",
		"ContractSignerType",
		"ContractStatus",
		"ContractSubtype",
		"ContractTermSubtype",
		"ContractTermType",
		"ContractType",
		"ContributorRole",
		"ContributorSummarySource",
		"ContributorSummaryStyle",
		"ContributorSummaryType",
		"ContributorType",
		"Country",
		"CoverageClass",
		"CoverageCopayType",
		"CoverageFinancialException",
		"CoverageKind",
		"CoverageType",
		"CoverageeligibilityresponseExAuthSupport",
		"Currencies N",
		"DataAbsentReason N",
		"DataTypes N",
		"Datestype",
		"DaysOfWeek N",
		"DefinitionMethod",
		"DefinitionResourceTypes N",
		"DefinitionTopic",
		"DefinitionUse N",
		"DesignationUse N",
		"DetectedissueCategory",
		"DetectedissueMitigationAction",
		"DetectedissueSeverity",
		"DetectedissueStatus",
		"DeviceAction",
		"DeviceAvailabilityStatus",
		"DeviceCategory",
		"DeviceCorrectiveactionscope",
		"DeviceNametype",
		"DeviceOperationMode",
		"DeviceProductidentifierinudi",
		"DevicePropertyType",
		"DeviceSafety",
		"DeviceSpecificationCategory",
		"DeviceSpecificationType",
		"DeviceStatus",
		"DeviceType",
		"DeviceVersiontype",
		"DeviceassociationOperationstatus",
		"DeviceassociationStatus",
		"DeviceassociationStatusReason",
		"DevicedefinitionRegulatoryIdentifierType",
		"DevicedefinitionRelationtype",
		"DevicedispenseStatus",
		"DevicedispenseStatusReason",
		"DevicemetricType",
		"DeviceusageAdherenceCode",
		"DeviceusageAdherenceReason",
		"DeviceusageStatus",
		"DiagnosisRole",
		"DiagnosticReportStatus",
		"DiagnosticServiceSections",
		"DietType",
		"DiscriminatorType N",
		"DiseaseStatus",
		"DiseaseSymptomProcedure",
		"DistanceUnits",
		"DocSectionCodes",
		"DocTypecodes",
		"DocumentMode N",
		"DocumentReferenceStatus",
		"DocumentRelationshipType",
		"DurationUnits N",
		"EdibleSubstanceType",
		"ElementdefinitionTypes N",
		"EligibilityOutcome",
		"EligibilityrequestPurpose",
		"EligibilityresponsePurpose",
		"EncounterAdmitSource",
		"EncounterDiagnosisUse",
		"EncounterDiet",
		"EncounterDischargeDisposition",
		"EncounterLocationStatus",
		"EncounterParticipantType",
		"EncounterReason",
		"EncounterReasonUse",
		"EncounterSpecialArrangements",
		"EncounterSpecialCourtesy",
		"EncounterStatus",
		"EncounterSubjectStatus",
		"EncounterType",
		"EndpointConnectionType",
		"EndpointEnvironment",
		"EndpointPayloadType",
		"EndpointStatus",
		"EnrollmentOutcome",
		"EnteralRoute",
		"EntformulaAdditive",
		"EntformulaType",
		"EpisodeOfCareStatus",
		"EpisodeofcareType",
		"EventCapabilityMode N",
		"EventResourceTypes N",
		"EventStatus",
		"EventTiming N",
		"EvidenceClassifierCode",
		"EvidenceReportSection",
		"EvidenceReportType",
		"EvidenceVariableEvent",
		"ExBenefitcategory",
		"ExDiagnosisOnAdmission",
		"ExDiagnosisrelatedgroup",
		"ExDiagnosistype",
		"ExPaymenttype",
		"ExProcedureType",
		"ExProgramCode",
		"ExRevenueCenter",
		"Example",
		"ExampleCptAll",
		"ExampleExpansion",
		"ExampleFilter",
		"ExampleIntensional",
		"ExampleMetadata",
		"ExampleMetadata2",
		"ExamplescenarioActorType",
		"ExamplescenarioInstanceType",
		"ExplanationofbenefitStatus",
		"ExpressionLanguage",
		"ExtensionContextType N",
		"FhirTypes N",
		"FhirpathTypes N",
		"FilterOperator N",
		"FlagCategory",
		"FlagCode",
		"FlagStatus",
		"FmStatus",
		"FocusCharacteristicCode",
		"FoodType",
		"Forms",
		"FormularyitemStatus",
		"Fundsreserve",
		"GenomicstudyChangetype",
		"GenomicstudyDataformat",
		"GenomicstudyMethodtype",
		"GenomicstudyStatus",
		"GenomicstudyType",
		"GoalAchievement",
		"GoalCategory",
		"GoalPriority",
		"GoalStartEvent",
		"GoalStatus",
		"GraphCompartmentRule",
		"GraphCompartmentUse",
		"GroupMembershipBasis",
		"GroupType",
		"GuidanceModuleCode",
		"GuidanceResponseStatus",
		"GuidePageGeneration",
		"GuideParameterCode",
		"HandlingCondition",
		"HistoryAbsentReason",
		"HistoryStatus",
		"HttpOperations",
		"HttpVerb N",
		"IanaLinkRelations N",
		"Icd10",
		"Icd10Procedures",
		"IdentifierType N",
		"IdentifierUse N",
		"IdentityAssurancelevel",
		"Imagingselection2Dgraphictype",
		"Imagingselection3Dgraphictype",
		"ImagingselectionStatus",
		"ImagingstudyStatus",
		"ImmunizationEvaluationDoseStatus",
		"ImmunizationEvaluationDoseStatusReason",
		"ImmunizationEvaluationStatus",
		"ImmunizationFunction",
		"ImmunizationFundingSource",
		"ImmunizationOrigin",
		"ImmunizationProgramEligibility",
		"ImmunizationReason",
		"ImmunizationRecommendationDateCriterion",
		"ImmunizationRecommendationReason",
		"ImmunizationRecommendationStatus",
		"ImmunizationRoute",
		"ImmunizationSite",
		"ImmunizationStatus",
		"ImmunizationStatusReason",
		"ImmunizationSubpotentReason",
		"ImmunizationTargetDisease",
		"ImmunizationVaccineFundingProgram",
		"Inactive",
		"IngredientFunction",
		"IngredientManufacturerRole",
		"IngredientRole",
		"InsuranceplanApplicability",
		"InsuranceplanType",
		"Interactant",
		"InteractionEffect",
		"InteractionIncidence",
		"InteractionManagement",
		"InteractionTrigger",
		"InteractionType",
		"InventoryitemNametype",
		"InventoryitemStatus",
		"InventoryreportCounttype",
		"InventoryreportStatus",
		"InvoiceStatus",
		"Iso316612",
		"Iso316613",
		"Iso31661N",
		"IssueSeverity N",
		"IssueType N",
		"ItemType",
		"Jurisdiction",
		"KnowledgeRepresentationLevel",
		"Languages N",
		"LegalStatusOfSupply",
		"LibraryType",
		"LinkType N",
		"LinkageType",
		"LipidLdlCodes",
		"ListEmptyReason",
		"ListExampleCodes",
		"ListItemFlag",
		"ListMode",
		"ListOrder",
		"ListStatus",
		"LocationCharacteristic",
		"LocationForm",
		"LocationMode",
		"LocationStatus",
		"ManifestationOrSymptom",
		"ManufacturedDoseForm",
		"MapGroupTypeMode",
		"MapInputMode",
		"MapModelMode",
		"MapSourceListMode",
		"MapTargetListMode",
		"MapTransform",
		"MaritalStatus N",
		"MeasureAggregateMethod",
		"MeasureDataUsage",
		"MeasureDefinitionExample",
		"MeasureGroupExample",
		"MeasureImprovementNotation",
		"MeasurePopulation",
		"MeasureReportStatus",
		"MeasureReportType",
		"MeasureScoringUnit",
		"MeasureStratifierExample",
		"MeasureSupplementalDataExample",
		"MeasureType",
		"MeasurementProperty",
		"MeasurereportStratifierValueExample",
		"MedAdminPerformFunction",
		"MedicationAdminLocation",
		"MedicationAdminStatus",
		"MedicationAsNeededReason",
		"MedicationCodes",
		"MedicationCostCategory",
		"MedicationDoseAid",
		"MedicationFormCodes",
		"MedicationIngredientstrength",
		"MedicationIntendedPerformerRole",
		"MedicationStatementAdherence",
		"MedicationStatementStatus",
		"MedicationStatus",
		"MedicationdispenseAdminLocation",
		"MedicationdispensePerformerFunction",
		"MedicationdispenseStatus",
		"MedicationdispenseStatusReason",
		"MedicationknowledgeCharacteristic",
		"MedicationknowledgeStatus",
		"MedicationrequestAdminLocation",
		"MedicationrequestCourseOfTherapy",
		"MedicationrequestIntent",
		"MedicationrequestStatus",
		"MedicationrequestStatusReason",
		"MedicinalProductAdditionalMonitoring",
		"MedicinalProductClassification",
		"MedicinalProductConfidentiality",
		"MedicinalProductContactType",
		"MedicinalProductCrossReferenceType",
		"MedicinalProductDomain",
		"MedicinalProductNamePartType",
		"MedicinalProductNameType",
		"MedicinalProductPackageType",
		"MedicinalProductPediatricUse",
		"MedicinalProductSpecialMeasures",
		"MedicinalProductType",
		"MessageEvents",
		"MessageReasonEncounter",
		"MessageSignificanceCategory",
		"MessageTransport N",
		"MessageheaderResponseRequest",
		"MetricCalibrationState",
		"MetricCalibrationType",
		"MetricCategory",
		"MetricOperationalStatus",
		"Mimetypes N",
		"MissingToothReason",
		"ModifiedFoodtype",
		"NameUse N",
		"NamingsystemIdentifierSystemType",
		"NamingsystemIdentifierType",
		"NamingsystemType",
		"NarrativeStatus",
		"NhinPurposeofuse",
		"NotConsumedReason",
		"NoteType",
		"NutrientCode",
		"NutritionProductCategory",
		"NutritionProductNutrient",
		"NutritionproductStatus",
		"ObjectRole",
		"ObservationCategory",
		"ObservationCodes",
		"ObservationInterpretation N",
		"ObservationMethods",
		"ObservationRangeCategory",
		"ObservationReferencerangeNormalvalue",
		"ObservationStatistics",
		"ObservationStatus N",
		"ObservationTriggeredbytype",
		"ObservationVitalsignresult",
		"OperationKind N",
		"OperationOutcome",
		"OperationParameterScope N",
		"OperationParameterUse N",
		"OrganizationRole",
		"OrganizationType",
		"OrientationType",
		"PackageMaterial",
		"PackageType",
		"PackagingType",
		"ParticipantResourceTypes N",
		"ParticipantRole",
		"ParticipationRoleType",
		"Participationstatus",
		"PatientContactrelationship N",
		"Payeetype",
		"PaymentAdjustmentReason",
		"PaymentIssuertype",
		"PaymentKind",
		"PaymentOutcome",
		"PaymentStatus",
		"PaymentType",
		"PerformerFunction",
		"PerformerRole",
		"PermissionRuleCombining",
		"PermissionStatus",
		"PermittedDataType",
		"PlanDefinitionType",
		"PractitionerRole",
		"PreparePatientPriorSpecimenCollection",
		"PriceComponentType",
		"ProcedureCategory",
		"ProcedureCode",
		"ProcedureFollowup",
		"ProcedureNotPerformedReason",
		"ProcedureOutcome",
		"ProcedureReason",
		"ProcessPriority",
		"ProductCategory",
		"ProductCharacteristicCodes",
		"ProductIntendedUse",
		"ProductStatus",
		"Program",
		"PropertyRepresentation N",
		"ProvenanceActivityType",
		"ProvenanceEntityRole",
		"ProvenanceHistoryAgentType",
		"ProvenanceHistoryRecordActivity",
		"ProviderQualification",
		"ProviderTaxonomy",
		"PublicationStatus N",
		"PublishedInType",
		"QuantityComparator N",
		"QuestionnaireAnswerConstraint",
		"QuestionnaireAnswers",
		"QuestionnaireAnswersStatus",
		"QuestionnaireDisabledDisplay",
		"QuestionnaireEnableBehavior",
		"QuestionnaireEnableOperator",
		"QuestionnaireQuestions",
		"ReactionEventSeverity",
		"ReasonMedicationGivenCodes",
		"ReasonMedicationNotGivenCodes",
		"ReasonMedicationStatusCodes",
		"ReferenceHandlingPolicy N",
		"ReferenceVersionRules N",
		"ReferencedItemCategory",
		"ReferencerangeAppliesto",
		"ReferencerangeMeaning",
		"RegulatedAuthorizationBasis",
		"RegulatedAuthorizationCaseType",
		"RegulatedAuthorizationType",
		"RejectionCriteria",
		"RelatedArtifactType",
		"RelatedArtifactTypeAll",
		"RelatedArtifactTypeExpanded",
		"RelatedClaimRelationship",
		"RelatedpersonRelationshiptype",
		"Relationship",
		"RemittanceOutcome",
		"ReportActionResultCodes",
		"ReportCodes",
		"ReportParticipantType",
		"ReportRelationType",
		"ReportResultCodes",
		"ReportStatusCodes",
		"RequestIntent",
		"RequestPriority",
		"RequestResourceTypes N",
		"RequestStatus",
		"ResearchStudyArmType",
		"ResearchStudyClassifiers",
		"ResearchStudyFocusType",
		"ResearchStudyObjectiveType",
		"ResearchStudyPartyOrganizationType",
		"ResearchStudyPartyRole",
		"ResearchStudyPhase",
		"ResearchStudyPrimPurpType",
		"ResearchStudyReasonStopped",
		"ResearchStudyStatus",
		"ResearchSubjectMilestone",
		"ResearchSubjectState",
		"ResearchSubjectStateType",
		"ResourceAggregationMode N",
		"ResourceSlicingRules N",
		"ResourceStatus",
		"ResourceTypes N",
		"ResourceValidationMode",
		"ResponseCode",
		"RestfulCapabilityMode N",
		"RestfulSecurityService N",
		"RiskProbability",
		"RouteCodes",
		"SearchComparator",
		"SearchEntryMode N",
		"SearchModifierCode",
		"SearchParamType N",
		"SearchProcessingmode",
		"SecurityLabelDataExamples",
		"SecurityLabelEventExamples",
		"SecurityLabelExamples",
		"SecurityLabels N",
		"SecurityRoleType",
		"SecuritySourceType",
		"SequenceType",
		"SeriesPerformerFunction",
		"ServiceCategory",
		"ServiceMode",
		"ServicePlace",
		"ServiceProvisionConditions",
		"ServiceReferralMethod",
		"ServiceType",
		"ServiceUscls",
		"ServicerequestCategory",
		"ServicerequestOrderdetailParameterCode",
		"SignatureType",
		"Slotstatus",
		"SortDirection",
		"SpdxLicense",
		"SpecimenCollection",
		"SpecimenCollectionMethod",
		"SpecimenCombined",
		"SpecimenContainedPreference",
		"SpecimenContainerType",
		"SpecimenProcessingMethod",
		"SpecimenRole",
		"SpecimenStatus",
		"StatisticModelCode",
		"StatisticType",
		"StrandType",
		"StructureDefinitionKind N",
		"StudyDesign",
		"SubmitDataUpdateType",
		"SubscriberRelationship",
		"SubscriptionChannelType",
		"SubscriptionError",
		"SubscriptionNotificationType",
		"SubscriptionPayloadContent",
		"SubscriptionStatus",
		"SubscriptionTypes N",
		"SubscriptiontopicCrBehavior",
		"SubstanceAmountType",
		"SubstanceCategory",
		"SubstanceCode",
		"SubstanceCodes",
		"SubstanceForm",
		"SubstanceGrade",
		"SubstanceNameAuthority",
		"SubstanceNameDomain",
		"SubstanceNameType",
		"SubstanceOpticalActivity",
		"SubstanceRelationshipType",
		"SubstanceRepresentationFormat",
		"SubstanceRepresentationType",
		"SubstanceSourceMaterialGenus",
		"SubstanceSourceMaterialPart",
		"SubstanceSourceMaterialSpecies",
		"SubstanceSourceMaterialType",
		"SubstanceStatus",
		"SubstanceStereochemistry",
		"SubstanceStructureTechnique",
		"SubstanceWeightMethod",
		"SubstanceWeightType",
		"SupplementType",
		"SupplyItem",
		"SupplydeliveryStatus",
		"SupplydeliverySupplyitemtype",
		"SupplyrequestKind",
		"SupplyrequestReason",
		"SupplyrequestStatus",
		"Surface",
		"SystemRestfulInteraction N",
		"TargetSpecies",
		"TaskCode",
		"TaskIntent",
		"TaskStatus",
		"TaskStatusReason",
		"TestscriptOperationCodes",
		"TestscriptProfileDestinationTypes",
		"TestscriptProfileOriginTypes",
		"TestscriptScopeConformanceCodes",
		"TestscriptScopePhaseCodes",
		"TextureCode",
		"Therapy",
		"TherapyRelationshipType",
		"Timezones",
		"TimingAbbreviation",
		"TitleType",
		"Tooth",
		"TransportCode",
		"TransportIntent",
		"TransportStatus",
		"TransportStatusReason",
		"TriggerType",
		"TypeDerivationRule N",
		"TypeRestfulInteraction N",
		"UcumBodylength",
		"UcumBodytemp",
		"UcumBodyweight",
		"UcumCommon",
		"UcumUnits",
		"UcumVitalsCommon",
		"UdiEntryType",
		"UndesirableEffectClassification",
		"UndesirableEffectFrequency",
		"UndesirableEffectSymptom",
		"UnitOfPresentation",
		"UnitsOfTime N",
		"UsageContextAgreementScope",
		"UseContext",
		"VaccineCode",
		"ValueFilterComparator",
		"VariableHandling",
		"VariableRole",
		"VerificationresultCanPushUpdates",
		"VerificationresultCommunicationMethod",
		"VerificationresultFailureAction",
		"VerificationresultNeed",
		"VerificationresultPrimarySourceType",
		"VerificationresultPushTypeAvailable",
		"VerificationresultStatus",
		"VerificationresultValidationProcess",
		"VerificationresultValidationStatus",
		"VerificationresultValidationType",
		"VersionAlgorithm",
		"VersionIndependentAllResourceTypes N",
		"VersionIndependentResourceTypes N",
		"VersioningPolicy N",
		"VirtualServiceType",
		"VisionBaseCodes",
		"VisionEyeCodes",
		"VisionProduct",
		"WarningType",
		"WeekOfMonth",
		"WrittenLanguages",
		"Yesnodontknow",
	}
)

func main() {
	fmt.Println("Hello World")
}
